[package]
name = "mlua_scheduler_ext"
version = "1.0.0"
edition = "2021"

[dependencies]
mlua = { git = "https://github.com/mlua-rs/mlua", branch = "dev", features = ["luau"] }
mlua_scheduler = { path = "../scheduler" }
log = "0.4"
tokio = { version = "1", features = ["rt", "sync"] }

[features]
default = ["fast"]
multithread = ["mlua_scheduler/send"]
fast = ["mlua_scheduler/fast"]