[package]
name = "mlua_scheduler_ext"
version = "1.0.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10", features = ["luau", "async"] }
mlua_scheduler = { path = "../scheduler" }
log = "0.4"
tokio = { version = "1", features = ["rt", "sync"] }

[features]
default = []
multithread = ["mlua_scheduler/send"]