[package]
name = "mlua_scheduler_cli"
version = "1.0.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10", features = ["luau", "async"] }
mlua_scheduler = { version = "1.0.0", path = "../scheduler" }
mlua_scheduler_ext = { version = "1.0.0", path = "../ext" }
tokio = { version = "1", features = ["rt"] }
clap = { version = "4.5.20", features = ["derive", "string"] }
env_logger = "0.11"

[features]
default = []
ncg = ["mlua/luau-jit"]
multithread = ["mlua_scheduler/send", "mlua_scheduler_ext/multithread"]