[package]
name = "mlua_scheduler"
version = "1.0.0"
edition = "2021"

[dependencies]
mlua = { version = "0.10.0", features = ["luau", "async"] }
smol = "2.0.2"
indexmap = "2.6.0"
flume = "0.11.1"
# async-task = "4.7.1"
# flume = "0.11.1"
tokio = { version = "1", features = ["rt", "macros", "fs", "time", "sync"] }
log = "0.4"
scc = "2"
