[package]
name = "mlua_scheduler"
version = "1.0.0"
edition = "2021"

[dependencies]
mlua = { git = "https://github.com/mlua-rs/mlua", features = ["luau"], rev = "cdd6a99136b90d028bf842865136060bd46ce335" }
tokio = { version = "1", features = ["rt", "macros", "fs", "time", "sync"] }
log = "0.4"
futures-util = "0.3.31"

[features]
default = []
